spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27018/booklibrary
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.13

mongock:
  migration-scan-package:
    - ru.otus.hw.mongock.changelog
  enabled: true