spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user_db
      username: user
      password: password
      authentication-database: admin
  shell:
    command:
      version:
        enabled: true

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
