spring:
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false
  shell:
    interactive:
      enabled: true

test:
  rightAnswersCountToPass: 3
  locale: ru-RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv
